### ISSUE TITLE
Can I use Express to build a server? Do I need to make a RESTful API?

### ISSUE THREAD

**Issue by pengjoshua** [BallenaDev/skills-90143#2]
Hi Ken,

This is my simple web app to display the ranking table for a soccer league given an input text file. One of the stipulations was that I am not to use any JavaScript frameworks. I understood this to mean that I cannot use Angular, React, etc for the frontend. I used the Express framework to build a simple server. Is this allowed? Please let me know if this is not allowed and I will build a server using only Node.

Also, am I supposed to hook up a database (MongoDB, MySQL, etc) to persist the data and enable full CRUD functionality and make a RESTful API? 

Thank you,
Joshua Peng

**Comment by BallenaDev** [comment]
Hi Joshua,

You are correct, for this exercise please do not use any frameworks like React or Angular. You are free to use jQuery and Bootstrap. For the back end portion, we would like to see an implementation using PHP, if that is possible. That will require setting up a simple server with Apache or nginx with PHP 5.6. Part of the exercise is to upload the data file to the server which should act as the data source, so there is no need to hook in a database. If you are to go the RESTful API route, I would only expect to see a GET verb to retrieve the league results. 

Let me know if I can provide further clarification.

Thanks!
Ken
