### ISSUE TITLE
Created PHP server, question about POST HTTP verb

### ISSUE THREAD

**Issue by pengjoshua** [BallenaDev/skills-90143#3]
Hi Ken,

Thank you for the clarification. I have created a simple PHP server that receives the text file as a JSON object and passes the processed ranking table as a JSON object back to the frontend. Since I use a file upload button on the frontend (so the user can browse for and select the data-input.txt file) and pass the data as a JSON object to the server, I think it makes sense to use a POST endpoint and request. 

I can instead load the text file directly on the backend by hardcoding in the text file filename so that I do not need to pass the data from the client and change it to a GET endpoint and request.

Please let me know what you think! 
https://github.com/pengjoshua/skills-90143

Thank you,
Joshua Peng

**Comment by BallenaDev** [comment]
Hi Joshua,

Thank you for submitting. The team and I will be reviewing on Friday. Please feel free to make any updates until Friday at 10:00am, at that point we will pull down and your code, review, and run it.

We are looking forward to reviewing your solution.

Thanks!
Ken

**Comment by pengjoshua** [comment]
Hi Ken,

Thank you Ken! I just wanted to let you know that I had a lot of fun
working on this project and look forward to your feedback on my code and
solution.

My fork of the project is located at:
https://github.com/pengjoshua/skills-90143

Thank you,
Joshua Peng

**Comment by BallenaDev** [comment]
Hi Joshua,

Thank you for working so hard on your solution. I am looking forward to reviewing!

Ken
